name: Devel

on:
  push:
    branches: [devel]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: ESLint
        run: yarn lint
      - name: Typescript
        run: yarn tsc
      - name: Run test
        run: yarn jest --coverage
      - name: Dicord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'La pull request a passé les tests avec succès ! PR mergé sur devel.'