name: CI staging

on:
  push:
    branches: [staging]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Test env Node v.${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Run ESLint
        run: yarn lint
      - name: Run Typescript
        run: yarn tsc
      - name: Run Jest tests
        run: yarn jest

  deploy_project:
    name: Build and deploy project
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just_a_placeholder_to_avoid_errors'
      - name: Adding know hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Build project
        run: NODE_ENV=production yarn build
      - name: Rsync project with server one
        run: rsync -r --exclude="package.json" . ${{ secrets.SERVER }}:${{ secrets.STAGING_FOLDER }}
      - name: Restart server
#        run: ssh ${{ secrets.SERVER }} pm2 reload ${{ secrets.STAGING_PROCESS_NAME }}

  publish_coverage:
    name: Publish code coverage
    needs: deploy_project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Run Jest tests
        run: yarn jest --coverage
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just_a_placeholder_to_avoid_errors'
      - name: Adding know hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Rsync tests report with server one
        run: rsync -r ./coverage/lcov-report/ ${{ secrets.SERVER }}:${{ secrets.STAGING_TEST }}